<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'office_name',
'full_name',
'mother_name',
'id_number',
'sex',
'birth',
'mobile_number',
'address',
'office_patinat_name',
'book_no',
'book_date',
'book_pic',
'book_attach',
'qr_code_info' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'office_name' => array( 'integrated_edit_field',
'integrated_edit_field1' ),
'full_name' => array( 'integrated_edit_field2',
'integrated_edit_field14' ),
'mother_name' => array( 'integrated_edit_field3',
'integrated_edit_field15' ),
'id_number' => array( 'integrated_edit_field4',
'integrated_edit_field16' ),
'sex' => array( 'integrated_edit_field5',
'integrated_edit_field17' ),
'birth' => array( 'integrated_edit_field6',
'integrated_edit_field18' ),
'mobile_number' => array( 'integrated_edit_field7',
'integrated_edit_field19' ),
'address' => array( 'integrated_edit_field8',
'integrated_edit_field20' ),
'office_patinat_name' => array( 'integrated_edit_field9',
'integrated_edit_field21' ),
'book_no' => array( 'integrated_edit_field10',
'integrated_edit_field22' ),
'book_date' => array( 'integrated_edit_field11',
'integrated_edit_field23' ),
'book_pic' => array( 'integrated_edit_field12',
'integrated_edit_field24' ),
'book_attach' => array( 'integrated_edit_field13',
'integrated_edit_field25' ),
'qr_code_info' => array( 'edit_field',
'edit_field_label' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field14',
'integrated_edit_field2',
'integrated_edit_field15',
'integrated_edit_field3',
'integrated_edit_field16',
'integrated_edit_field4',
'integrated_edit_field17',
'integrated_edit_field5',
'integrated_edit_field18',
'integrated_edit_field6',
'integrated_edit_field19',
'integrated_edit_field7',
'integrated_edit_field20',
'integrated_edit_field8',
'integrated_edit_field21',
'integrated_edit_field9',
'integrated_edit_field22',
'integrated_edit_field10',
'integrated_edit_field23',
'integrated_edit_field11',
'integrated_edit_field24',
'integrated_edit_field12',
'integrated_edit_field25',
'integrated_edit_field13',
'edit_field_label',
'edit_field' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field13' => 'grid',
'edit_field_label' => 'grid',
'edit_field' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'edit_field' => array( 'location' => 'grid',
'cellId' => 'c28' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'edit_field_label' => array( 'integrated_edit_field',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'edit_field_label' ),
'edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'edit_field' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'office_name_fieldblock' ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'full_name_fieldblock' ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'mother_name_fieldblock' ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'id_number_fieldblock' ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'sex_fieldblock' ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'birth_fieldblock' ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'mobile_number_fieldblock' ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'address_fieldblock' ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'office_patinat_name_fieldblock' ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'book_no_fieldblock' ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'book_date_fieldblock' ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'book_pic_fieldblock' ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'book_attach_fieldblock' ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'qr_code_info_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 14 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field' ),
'field' => 'office_name',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field1' ),
'field' => 'office_name',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field14' ),
'field' => 'full_name',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c3' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field2' ),
'field' => 'full_name',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c5' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field15' ),
'field' => 'mother_name',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field3' ),
'field' => 'mother_name',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c7' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field16' ),
'field' => 'id_number',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ),
'field' => 'id_number',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c9' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field17' ),
'field' => 'sex',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c10' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field5' ),
'field' => 'sex',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c11' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field18' ),
'field' => 'birth',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c12' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'field' => 'birth',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c13' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field19' ),
'field' => 'mobile_number',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c14' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field7' ),
'field' => 'mobile_number',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c15' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field20' ),
'field' => 'address',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c16' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field8' ),
'field' => 'address',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c17' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field21' ),
'field' => 'office_patinat_name',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c18' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field9' ),
'field' => 'office_patinat_name',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c19' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field22' ),
'field' => 'book_no',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c20' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field10' ),
'field' => 'book_no',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c21' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field23' ),
'field' => 'book_date',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c22' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field11' ),
'field' => 'book_date',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c23' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field24' ),
'field' => 'book_pic',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c24' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field12' ),
'field' => 'book_pic',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c25' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field25' ),
'field' => 'book_attach',
'align' => 'center',
'color' => '#ffffff',
'background' => '#616161',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c26' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field13' ),
'field' => 'book_attach',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ),
'c27' => array( 'model' => 'c4',
'items' => array( 'edit_field_label' ),
'field' => 'qr_code_info',
'align' => 'center',
'background' => '#616161',
'color' => '#ffffff',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#ffffff' ) ),
'bold' => true,
'font-size' => '20px' ),
'c28' => array( 'model' => 'c2',
'items' => array( 'edit_field' ),
'field' => 'qr_code_info',
'border' => array( array( 'side' => '',
'width' => '2px',
'color' => '#000000' ) ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'info_patinat',
'type' => 7 ) ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'type' => 'edit_field_label',
'field' => 'office_name' ),
'integrated_edit_field1' => array( 'field' => 'office_name',
'type' => 'edit_field' ),
'integrated_edit_field2' => array( 'field' => 'full_name',
'type' => 'edit_field' ),
'integrated_edit_field3' => array( 'field' => 'mother_name',
'type' => 'edit_field' ),
'integrated_edit_field4' => array( 'field' => 'id_number',
'type' => 'edit_field' ),
'integrated_edit_field5' => array( 'field' => 'sex',
'type' => 'edit_field' ),
'integrated_edit_field6' => array( 'field' => 'birth',
'type' => 'edit_field' ),
'integrated_edit_field7' => array( 'field' => 'mobile_number',
'type' => 'edit_field' ),
'integrated_edit_field8' => array( 'field' => 'address',
'type' => 'edit_field' ),
'integrated_edit_field9' => array( 'field' => 'office_patinat_name',
'type' => 'edit_field' ),
'integrated_edit_field10' => array( 'field' => 'book_no',
'type' => 'edit_field' ),
'integrated_edit_field11' => array( 'field' => 'book_date',
'type' => 'edit_field' ),
'integrated_edit_field12' => array( 'field' => 'book_pic',
'type' => 'edit_field' ),
'integrated_edit_field13' => array( 'field' => 'book_attach',
'type' => 'edit_field' ),
'integrated_edit_field14' => array( 'type' => 'edit_field_label',
'field' => 'full_name' ),
'integrated_edit_field15' => array( 'type' => 'edit_field_label',
'field' => 'mother_name' ),
'integrated_edit_field16' => array( 'type' => 'edit_field_label',
'field' => 'id_number' ),
'integrated_edit_field17' => array( 'type' => 'edit_field_label',
'field' => 'sex' ),
'integrated_edit_field18' => array( 'type' => 'edit_field_label',
'field' => 'birth' ),
'integrated_edit_field19' => array( 'type' => 'edit_field_label',
'field' => 'mobile_number' ),
'integrated_edit_field20' => array( 'type' => 'edit_field_label',
'field' => 'address' ),
'integrated_edit_field21' => array( 'type' => 'edit_field_label',
'field' => 'office_patinat_name' ),
'integrated_edit_field22' => array( 'type' => 'edit_field_label',
'field' => 'book_no' ),
'integrated_edit_field23' => array( 'type' => 'edit_field_label',
'field' => 'book_date' ),
'integrated_edit_field24' => array( 'type' => 'edit_field_label',
'field' => 'book_pic' ),
'integrated_edit_field25' => array( 'type' => 'edit_field_label',
'field' => 'book_attach' ),
'edit_field' => array( 'field' => 'qr_code_info',
'type' => 'edit_field' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'qr_code_info' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>