<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_info_patinat  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeQueryView"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$data = array();
$keyvalues = array();
$cod_id=$values['id'].  rand(1000, 5000000);
 
$data["qr_code_info"] = "http://localhost/decisions1/info_patinat_view_view.php?editid1=".$cod_id."&editid2=876678654";
 $data['id_search']=$cod_id;
$keyvalues["id"] = $values["id"];
DB::Update("info_patinat", $data, $keyvalues );



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// View page: Before SQL query
function BeforeQueryView(&$strSQL, &$strWhereClause, $pageObject)
{

		if($_GET['editid2']=='876678654'){
$strWhereClause="id_search=".$_GET['editid1'];// Place event code here.
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeQueryView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
